# Site settings
title: VerkaDrobka s. r. o.
email: your-email@domain.com
url: "http://verkadrobka.cz"
port: 3000
host:
description: Kompletní služby v oboru celní problematiky

color:
  primary: a9a9a9
  secondary: 696969
  secondary-dark: 808080

markdown: kramdown
permalink: pretty

exclude: ["Gemfile*", "README.md", "LICENCE"]

