# Site settings
title: VerkaDrobka s. r. o.
email: your-email@domain.com
url: "http://localhost:3001"
port: 3000
host:
description: Kompletní služby v oboru celní problematiky

color:
  primary: 05C2FA
  secondary: 2c3e50
  secondary-dark: 233140

markdown: kramdown
permalink: pretty
