# Site settings
title: Freelancer
email: your-email@domain.com
url: "http://127.0.0.1:3001"
port: 3000
host:
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

color:
  primary: 18bc9c
  secondary: 2c3e50
  secondary-dark: 233140

footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

social:
  - title: facebook
    url:

address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

markdown: kramdown
permalink: pretty
